[package]
name = "webir_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swc_common = "0.33.19"
swc_ecma_parser = "0.170.0"
jsonschema = "0.17"
