name: Publish Gleam Bindings

on:
  workflow_dispatch:
  push:
    tags:
      - 'bindings-v*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Emit Gleam bindings
        run: bun emit gleam

      - name: Set up Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: false
          gleam-version: '1.10.0'

      - name: Format and build package
        run: |
          cd bindings/gleam/twig
          gleam format
          gleam build

      - name: Publish to Hex.pm
        env:
          HEXPM_API_KEY: ${{ secrets.HEXPM_API_KEY }}
        run: |
          cd bindings/gleam/twig
          gleam publish --yes
