name: Regenerate IR on TypeScript Changes

on:
  push:
    branches: [main]
    paths:
      - "package.json"
      - "bun.lockb"
  workflow_dispatch:

jobs:
  regenerate-ir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Extract IR
        run: bun run extract -o dom-api-ir.json

      - name: Validate IR
        run: bun run validate -i dom-api-ir.json

      - name: Get TypeScript version
        id: typescript_version
        run: echo "version=$(bun x tsc -v | cut -d ' ' -f2)" >> $GITHUB_OUTPUT

      - name: Commit and push IR if changed
        run: |
          git config user.name "IR Bot"
          git config user.email "ir-bot@users.noreply.github.com"
          git add dom-api-ir.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            VERSION=${{ steps.typescript_version.outputs.version }}
            git commit -m "chore: regenerate IR using TypeScript v$VERSION"
            git tag "typescript-v$VERSION"
            git push origin main --follow-tags
          fi
