name: Regenerate IR on TypeScript Changes

on:
  push:
    branches: [main]
    paths:
      - "package.json"
      - "bun.lockb"
  workflow_dispatch:

jobs:
  regenerate-ir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Extract IR
        run: bun run extract -o dom-api-ir.json

      - name: Validate IR
        run: bun run validate -i dom-api-ir.json

      - name: Get TypeScript version
        id: typescript_version
        run: echo "version=$(bun x tsc -v | cut -d ' ' -f2)" >> $GITHUB_OUTPUT

      - name: Commit and push IR with tag
        run: |
          git config user.name "IR Bot"
          git config user.email "ir-bot@users.noreply.github.com"
          git add dom-api-ir.json

          VERSION=${{ steps.typescript_version.outputs.version }}

          if git diff --cached --quiet; then
            echo "No IR changes to commit"
          else
            TAG="typescript-v$VERSION"
            git commit -m "chore: regenerate IR using TypeScript v$VERSION"
            git tag -f "$TAG"
            git tag -f latest

            REPO="https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}"
            git push "$REPO" HEAD:main
            git push "$REPO" "$TAG" --force
            git push "$REPO" latest --force
          fi
