name: Regenerate IR on TypeScript Changes

on:
  push:
    branches: [main]
    paths:
      - "package.json"
      - "bun.lockb"
  workflow_dispatch:

jobs:
  regenerate-ir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Extract IR
        run: bun run extract -o dom-api-ir.json

      - name: Validate IR
        run: bun run validate -i dom-api-ir.json

      - name: Get TypeScript version
        id: typescript_version
        run: echo "version=$(bun x tsc -v | cut -d ' ' -f2)" >> $GITHUB_OUTPUT

      - name: Commit and push IR with tags
        env:
          github_token: ${{ secrets.github_token }}
          github_repository: ${{ github.repository }}
          version: ${{ steps.typescript_version.outputs.version }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
          git add dom-api-ir.json
          echo "$version" > .last-typescript-version
          git add .last-typescript-version
      
          if git diff --cached --quiet; then
            echo "No IR changes to commit"
          else
            git commit -m "chore: regenerate IR using TypeScript v$version"
            git tag -f "typescript-v$version"
            git tag -f latest
      
            echo "Pushing using PAT"
            git push https://x-access-token:$github_token@github.com/$github_repository HEAD:main
            git push https://x-access-token:$github_token@github.com/$github_repository "typescript-v$version" --force
            git push https://x-access-token:$github_token@github.com/$github_repository latest --force
          fi

